import { Geist, Geist_Mono } from "next/font/google";
import Navbar from './components/Navbar'
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-orange-50`} 
      >
        <Navbar />
        {children}

        <footer className="bg-amber-900 text-white py-6 mt-10">
          <div className="max-w-7xl mx-auto px-4 text-center">
            <p>2025 Addict Bite Cookie. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
